/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as DaemonRouteImport } from './routes/daemon'
import { Route as HwihfRouteImport } from './routes/hwihf'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LinksRouteImport } from './routes/links'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts.index'
import { Route as ArtifactsArtifactIdRouteImport } from './routes/artifacts.$artifactId'
import { Route as ArtifactsArtifactIdActivityRouteImport } from './routes/artifacts.$artifactId.activity'
import { Route as ArtifactsArtifactIdEvidenceRouteImport } from './routes/artifacts.$artifactId.evidence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const DaemonRoute = DaemonRouteImport.update({
  id: '/daemon',
  path: '/daemon',
  getParentRoute: () => rootRouteImport,
} as any)
const HwihfRoute = HwihfRouteImport.update({
  id: '/hwihf',
  path: '/hwihf',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/artifacts/',
  path: '/artifacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: '/artifacts/$artifactId',
  path: '/artifacts/$artifactId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsArtifactIdActivityRoute =
  ArtifactsArtifactIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ArtifactsArtifactIdRoute,
  } as any)
const ArtifactsArtifactIdEvidenceRoute =
  ArtifactsArtifactIdEvidenceRouteImport.update({
    id: '/evidence',
    path: '/evidence',
    getParentRoute: () => ArtifactsArtifactIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/assess': typeof AssessRoute
  '/daemon': typeof DaemonRoute
  '/hwihf': typeof HwihfRoute
  '/legal': typeof LegalRoute
  '/links': typeof LinksRoute
  '/models': typeof ModelsRoute
  '/operator': typeof OperatorRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/use-cases': typeof UseCasesRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRouteWithChildren
  '/artifacts/': typeof ArtifactsIndexRoute
  '/artifacts/$artifactId/activity': typeof ArtifactsArtifactIdActivityRoute
  '/artifacts/$artifactId/evidence': typeof ArtifactsArtifactIdEvidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/assess': typeof AssessRoute
  '/daemon': typeof DaemonRoute
  '/hwihf': typeof HwihfRoute
  '/legal': typeof LegalRoute
  '/links': typeof LinksRoute
  '/models': typeof ModelsRoute
  '/operator': typeof OperatorRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/use-cases': typeof UseCasesRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRouteWithChildren
  '/artifacts': typeof ArtifactsIndexRoute
  '/artifacts/$artifactId/activity': typeof ArtifactsArtifactIdActivityRoute
  '/artifacts/$artifactId/evidence': typeof ArtifactsArtifactIdEvidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/assess': typeof AssessRoute
  '/daemon': typeof DaemonRoute
  '/hwihf': typeof HwihfRoute
  '/legal': typeof LegalRoute
  '/links': typeof LinksRoute
  '/models': typeof ModelsRoute
  '/operator': typeof OperatorRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/use-cases': typeof UseCasesRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRouteWithChildren
  '/artifacts/': typeof ArtifactsIndexRoute
  '/artifacts/$artifactId/activity': typeof ArtifactsArtifactIdActivityRoute
  '/artifacts/$artifactId/evidence': typeof ArtifactsArtifactIdEvidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/assess'
    | '/daemon'
    | '/hwihf'
    | '/legal'
    | '/links'
    | '/models'
    | '/operator'
    | '/security'
    | '/services'
    | '/team'
    | '/terms'
    | '/tools'
    | '/use-cases'
    | '/artifacts/$artifactId'
    | '/artifacts/'
    | '/artifacts/$artifactId/activity'
    | '/artifacts/$artifactId/evidence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/assess'
    | '/daemon'
    | '/hwihf'
    | '/legal'
    | '/links'
    | '/models'
    | '/operator'
    | '/security'
    | '/services'
    | '/team'
    | '/terms'
    | '/tools'
    | '/use-cases'
    | '/artifacts/$artifactId'
    | '/artifacts'
    | '/artifacts/$artifactId/activity'
    | '/artifacts/$artifactId/evidence'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/assess'
    | '/daemon'
    | '/hwihf'
    | '/legal'
    | '/links'
    | '/models'
    | '/operator'
    | '/security'
    | '/services'
    | '/team'
    | '/terms'
    | '/tools'
    | '/use-cases'
    | '/artifacts/$artifactId'
    | '/artifacts/'
    | '/artifacts/$artifactId/activity'
    | '/artifacts/$artifactId/evidence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AssessRoute: typeof AssessRoute
  DaemonRoute: typeof DaemonRoute
  HwihfRoute: typeof HwihfRoute
  LegalRoute: typeof LegalRoute
  LinksRoute: typeof LinksRoute
  ModelsRoute: typeof ModelsRoute
  OperatorRoute: typeof OperatorRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  UseCasesRoute: typeof UseCasesRoute
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRouteWithChildren
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daemon': {
      id: '/daemon'
      path: '/daemon'
      fullPath: '/daemon'
      preLoaderRoute: typeof DaemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hwihf': {
      id: '/hwihf'
      path: '/hwihf'
      fullPath: '/hwihf'
      preLoaderRoute: typeof HwihfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$artifactId': {
      id: '/artifacts/$artifactId'
      path: '/artifacts/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$artifactId/activity': {
      id: '/artifacts/$artifactId/activity'
      path: '/activity'
      fullPath: '/artifacts/$artifactId/activity'
      preLoaderRoute: typeof ArtifactsArtifactIdActivityRouteImport
      parentRoute: typeof ArtifactsArtifactIdRoute
    }
    '/artifacts/$artifactId/evidence': {
      id: '/artifacts/$artifactId/evidence'
      path: '/evidence'
      fullPath: '/artifacts/$artifactId/evidence'
      preLoaderRoute: typeof ArtifactsArtifactIdEvidenceRouteImport
      parentRoute: typeof ArtifactsArtifactIdRoute
    }
  }
}

interface ArtifactsArtifactIdRouteChildren {
  ArtifactsArtifactIdActivityRoute: typeof ArtifactsArtifactIdActivityRoute
  ArtifactsArtifactIdEvidenceRoute: typeof ArtifactsArtifactIdEvidenceRoute
}

const ArtifactsArtifactIdRouteChildren: ArtifactsArtifactIdRouteChildren = {
  ArtifactsArtifactIdActivityRoute: ArtifactsArtifactIdActivityRoute,
  ArtifactsArtifactIdEvidenceRoute: ArtifactsArtifactIdEvidenceRoute,
}

const ArtifactsArtifactIdRouteWithChildren =
  ArtifactsArtifactIdRoute._addFileChildren(ArtifactsArtifactIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AssessRoute: AssessRoute,
  DaemonRoute: DaemonRoute,
  HwihfRoute: HwihfRoute,
  LegalRoute: LegalRoute,
  LinksRoute: LinksRoute,
  ModelsRoute: ModelsRoute,
  OperatorRoute: OperatorRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  UseCasesRoute: UseCasesRoute,
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRouteWithChildren,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
